name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - pandas
      - numpy
      - scikit-learn<=1.5.2
      - mlflow==2.18.0
      - matplotlib
      - seaborn
