name: MLflow CI - Model Retraining

on:
  push:
    branches: [ main ]
    paths:
      - 'MLProject/**'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  train-and-track:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install MLflow & dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.18.0 pandas numpy "scikit-learn<=1.5.2" matplotlib seaborn

      - name: Run MLflow Project (retraining)
        working-directory: MLProject
        run: |
          mlflow run . --env-manager=local

      # --- Simpan artefak sebagai GitHub Actions artifact (bisa diunduh dari tab Actions) ---
      - name: Upload MLflow run as GitHub Actions artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-run-artifacts
          path: MLProject/mlruns

      # --- Simpan artefak ke repository GitHub yang sama (commit & push) ---
      - name: Commit & push mlruns to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add MLProject/mlruns
          git diff --staged --quiet || git commit -m "ci: update MLflow tracking artifacts [skip ci]"
          git push
